name: Home Manager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  home-manager:
    name: Home Manager
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Test
      run: |
        # Redirect stderr to stdout, because GitHub Actions is bad at
        # preserving order between the two separate streams.
        exec 2>&1

        set -x
        lazyssh_src="${PWD}"
        hm_config="${HOME}/hm-config"
        hm_build="${HOME}/hm-build"

        # Prepare a directory with LazySSH and Home Manager configuration.
        mkdir "${hm_config}"

        ssh-keygen -t ed25519 -f "${hm_config}/dummy-key" < /dev/null

        cat > "${hm_config}/lazyssh.hcl" << EOF
        server {
          host_key = <<DUMMY
        $(<"${hm_config}/dummy-key")
        DUMMY
          authorized_key = <<DUMMY
        $(<"${hm_config}/dummy-key.pub")
        DUMMY
        }
        EOF

        cat > "${hm_config}/flake.nix" << EOF
        {
          inputs.home-manager.url = "github:nix-community/home-manager";
          inputs.lazyssh.url = "${lazyssh_src}";
          outputs = { home-manager, lazyssh, ... }: {
            homeManagerConfiguration = home-manager.lib.homeManagerConfiguration {
              system = "x86_64-linux";
              username = "runner";
              homeDirectory = "${HOME}";
              configuration = {
                imports = [ lazyssh.homeManagerModule ];
                services.lazyssh.configFile = "${hm_config}/lazyssh.hcl";
                home.stateVersion = "20.09";
              };
            };
          };
        }
        EOF

        # Build the Home Manager configuration.
        nix build -v -o "${hm_build}" \
          "${hm_config}#homeManagerConfiguration.activationPackage"

        # Start the user systemd, so Home Manager can start services.
        sudo install -d -m 0700 -o "${USER}" "/run/user/${UID}"
        export XDG_RUNTIME_DIR="/run/user/${UID}"
        sudo systemctl start "user@${UID}.service"

        # Activate Home Manager and start LazySSH.
        "${hm_build}/activate"
        systemctl --user start lazyssh.service

        # Verify LazySSH is running.
        tries=10
        while ! nc -vz 127.0.0.1 7922; do
          if [[ $((--tries)) -eq 0 ]]; then
            echo >&2 'Timed out waiting for LazySSH to start'
            journalctl --user
            exit 1
          fi
          sleep 1
        done
